### ISSUE TITLE
test-failure  MathematicalOperationsTest.testPower

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#48]
```
testPower(MathematicalOperationsTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertEquals(Assert.java:667)
    at org.junit.Assert.assertEquals(Assert.java:656)
    at MathematicalOperationsTest.testPower(MathematicalOperationsTest.java:49)
```

**Comment by fthdgn** [comment]
Closed via 2a61ea5b01f0305996b7a6d3acf072adcfe0410f
